using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using PropertyChanged.SourceGenerator.Analysis;

namespace PropertyChanged.SourceGenerator
{
    public class Generator
    {
        private readonly IndentedTextWriter writer = new(new StringWriter());
        private readonly HashSet<string> nameCacheEntries;

        public static string FileHeader { get; } = @$"// <auto-generated>
//     Auto-generated by PropertyChanged.SourceGenerator {typeof(Generator).Assembly.GetName().Version}
// </auto-generated>";

        public Generator(HashSet<string> nameCacheEntries)
        {
            this.nameCacheEntries = nameCacheEntries;
         
            this.writer.WriteLine(FileHeader);
        }

        public void Generate(TypeAnalysis typeAnalysis)
        {
            // SG'd files default to 'disable'
            if (typeAnalysis.NullableContext != NullableContextOptions.Disable)
            {
                this.writer.WriteLine(NullableContextToComment(typeAnalysis.NullableContext));
            }

            if (typeAnalysis.TypeSymbol.ContainingNamespace is { IsGlobalNamespace: false } @namespace)
            {
                this.writer.WriteLine($"namespace {@namespace.ToDisplayString(SymbolDisplayFormats.Namespace)}");
                this.writer.WriteLine("{");
                this.writer.Indent++;

                this.GenerateType(typeAnalysis);

                this.writer.Indent--;
                this.writer.WriteLine("}");
            }
            else
            {
                this.GenerateType(typeAnalysis);
            }
        }

        private void GenerateType(TypeAnalysis typeAnalysis)
        {
            this.writer.Write($"partial {typeAnalysis.TypeSymbol.ToDisplayString(SymbolDisplayFormats.TypeDeclaration)}");
            if (!typeAnalysis.HasInpcInterface)
            {
                this.writer.Write(" : global::System.ComponentModel.INotifyPropertyChanged");
            }
            this.writer.WriteLine();
            
            this.writer.WriteLine("{");
            this.writer.Indent++;

            if (typeAnalysis.RequiresEvent)
            {
                string nullable = typeAnalysis.NullableContext.HasFlag(NullableContextOptions.Annotations) ? "?" : "";
                this.writer.WriteLine($"public event global::System.ComponentModel.PropertyChangedEventHandler{nullable} PropertyChanged;");
            }

            foreach (var member in typeAnalysis.Members)
            {
                this.GenerateMember(typeAnalysis, member);
            }

            if (typeAnalysis.RequiresRaisePropertyChangedMethod)
            {
                Trace.Assert(typeAnalysis.RaisePropertyChangedMethodSignature == RaisePropertyChangedMethodSignature.PropertyChangedEventArgs);
                this.writer.WriteLine($"protected virtual void {typeAnalysis.RaisePropertyChangedMethodName}(global::System.ComponentModel.PropertyChangedEventArgs eventArgs)");
                this.writer.WriteLine("{");
                this.writer.Indent++;

                this.writer.WriteLine("this.PropertyChanged?.Invoke(this, eventArgs);");

                this.writer.Indent--;
                this.writer.WriteLine("}");
            }

            this.writer.Indent--;
            this.writer.WriteLine("}");
        }

        private void GenerateMember(TypeAnalysis type, MemberAnalysis member)
        {
            string backingMemberReference = "this." + member.BackingMember.ToDisplayString(SymbolDisplayFormats.SymbolName);

            if (member.NullableContextOverride is { } context)
            {
                this.writer.WriteLine(NullableContextToComment(context));
            }

            var (propertyAccessibility, getterAccessibility, setterAccessibility) = CalculateAccessibilities(member);

            this.writer.WriteLine($"{propertyAccessibility}{member.Type.ToDisplayString(SymbolDisplayFormats.MethodOrPropertyReturnType)} {member.Name}");
            this.writer.WriteLine("{");
            this.writer.Indent++;

            this.writer.WriteLine($"{getterAccessibility}get => {backingMemberReference};");
            this.writer.WriteLine($"{setterAccessibility}set");
            this.writer.WriteLine("{");
            this.writer.Indent++;

            this.writer.WriteLine("if (!global::System.Collections.Generic.EqualityComparer<" +
                member.Type.ToDisplayString(SymbolDisplayFormats.TypeParameter) +
                $">.Default.Equals(value, {backingMemberReference}))");
            this.writer.WriteLine("{");
            this.writer.Indent++;

            this.writer.WriteLine($"{backingMemberReference} = value;");

            this.GenerateRaiseEvent(type, member);

            this.writer.Indent--;
            this.writer.WriteLine("}");
            this.writer.Indent--;
            this.writer.WriteLine("}");
            this.writer.Indent--;
            this.writer.WriteLine("}");

            if (member.NullableContextOverride != null)
            {
                this.writer.WriteLine(NullableContextToComment(type.NullableContext));
            }
        }

        private void GenerateRaiseEvent(TypeAnalysis type, MemberAnalysis member)
        {
            switch (type.RaisePropertyChangedMethodSignature)
            {
                case RaisePropertyChangedMethodSignature.PropertyChangedEventArgs:
                    this.nameCacheEntries.Add(member.Name);
                    this.writer.WriteLine($"this.{type.RaisePropertyChangedMethodName}(global::PropertyChanged.SourceGenerator.Internal.PropertyChangedEventArgsCache.{member.Name});");
                    break;

                case RaisePropertyChangedMethodSignature.String:
                    this.writer.WriteLine($"this.{type.RaisePropertyChangedMethodName}(\"{member.Name}\");");
                    break;
            }
        }

        private static (string property, string getter, string setter) CalculateAccessibilities(MemberAnalysis member)
        {
            string property;
            string getter = "";
            string setter = "";

            if (member.GetterAccessibility >= member.SetterAccessibility)
            {
                property = AccessibilityToString(member.GetterAccessibility);
                setter = member.GetterAccessibility == member.SetterAccessibility
                    ? ""
                    : AccessibilityToString(member.SetterAccessibility);
            }
            else
            {
                property = AccessibilityToString(member.SetterAccessibility);
                getter = AccessibilityToString(member.GetterAccessibility);
            }

            return (property, getter, setter);
        }

        private static string NullableContextToComment(NullableContextOptions context)
        {
            return context switch
            {
                NullableContextOptions.Disable => "#nullable disable",
                NullableContextOptions.Warnings => "#nullable enable warnings",
                NullableContextOptions.Annotations => "#nullable enable annotations",
                NullableContextOptions.Enable => "#nullable enable"
            };
        }

        private static string AccessibilityToString(Accessibility accessibility)
        {
            return accessibility switch
            {
                Accessibility.Public => "public ",
                Accessibility.ProtectedOrInternal => "protected internal ",
                Accessibility.Internal => "internal ",
                Accessibility.Protected => "protected ",
                Accessibility.ProtectedAndInternal => "private protected ",
                Accessibility.Private => "private ",
                _ => throw new ArgumentException("Unknown member", nameof(accessibility)),
            };
        }

        public void GenerateNameCache()
        {
            this.writer.WriteLine("namespace PropertyChanged.SourceGenerator.Internal");
            this.writer.WriteLine("{");
            this.writer.Indent++;

            this.writer.WriteLine("internal static class PropertyChangedEventArgsCache");
            this.writer.WriteLine("{");
            this.writer.Indent++;

            foreach (string name in this.nameCacheEntries.OrderBy(x => x))
            {
                string backingFieldName = "_" + name;
                for (int i = 0; this.nameCacheEntries.Contains(backingFieldName); i++)
                {
                    backingFieldName = $"_{name}{i}";
                }
                this.writer.WriteLine($"private static global::System.ComponentModel.PropertyChangedEventArgs {backingFieldName};");
                this.writer.WriteLine($"public static global::System.ComponentModel.PropertyChangedEventArgs {name} => " +
                    $"{backingFieldName} ??= new global::System.ComponentModel.PropertyChangedEventArgs(\"{name}\");");
            }

            this.writer.Indent--;
            this.writer.WriteLine("}");

            this.writer.Indent--;
            this.writer.WriteLine("}");
        }

        public override string ToString() => this.writer.InnerWriter.ToString();
    }
}
